sudo: required
services:
  - docker 
before_install:
  - docker build -t kanth77/react-test -f ./client/Dockerfile

script:
  - docker run -e CI=true kanth77/react-test npm test

after_success:
  - docker build -t kanth77/multi-client ./client
  - docker build -t kanth77/multi-ngnix ./ngnix
  - docker build -t kanth77/multi-server ./server
  - docker build -t kanth77/multi-worker ./worker
  # login into docker CLI
  -  echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-s
  #Take those images and push to dockerhub
  - docker push kanth77/multi-client
  - docker push kanth77/multi-ngnix
  - docker push kanth77/multi-server
  - docker push kanth77/multi-worker
